/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventav2;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Rafael
 */
public final class frmclientes extends javax.swing.JFrame {
  public static final String db="bdpuntoventa";
   private static final String User="root";
   private static final String pass="0547";
   static String url = "jdbc:mysql://localhost:3306/"+db+"?serverTimezone=UTC";
    private static Connection Conn=null; 
     static ResultSet rs=null;
    private Statement stmt=null;
    conectar conexion = new conectar();
    Object filas[]= new Object[7];                          //objeto que utilizare para llenar la 
//                Conn = conexion.getConeConnection();
                
             Connection con = null;
   /**
     * Creates new form frmclientes
     */
                 int b=0; // variable para contar las columnas de la tabla y poder borrar
    public frmclientes() {
        initComponents();
        ultimoRegistro();
      this.setResizable(false);
      salir();
    }
     public void salir()
      {
          try 
          {
              this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
              addWindowListener(new WindowAdapter() 
              {
                  @Override
                  public void windowClosing(WindowEvent e)
                  {
                    frmPrincipal.habilitar();
                      cerrar();
                  }
                  
              } );
              this.setVisible(true);
          }
          catch (Exception e) 
          {
              e.printStackTrace();
          }
      } 
        void cerrar() 
        {
            this.dispose();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbmetodopago = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtdiascredito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcolonia = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombrecliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNoCliente = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.orange);

        jPanel1.setBackground(new java.awt.Color(214, 214, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registro de Clientes");

        jPanel2.setBackground(new java.awt.Color(214, 214, 251));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Dias de Credito:");

        cmbmetodopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        cmbmetodopago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmetodopagoItemStateChanged(evt);
            }
        });
        cmbmetodopago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbmetodopagoFocusLost(evt);
            }
        });
        cmbmetodopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmetodopagoActionPerformed(evt);
            }
        });
        cmbmetodopago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbmetodopagoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Metodo de Pago:");

        txtdiascredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdiascredito.setEnabled(false);
        txtdiascredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiascreditoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiascreditoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Colonia:");

        txtcolonia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcolonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcoloniaKeyPressed(evt);
            }
        });

        txtdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Direccion:");

        txtnombrecliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombrecliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreclienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreclienteKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("N° Cliente:");

        lblNoCliente.setBackground(new java.awt.Color(255, 102, 102));
        lblNoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNoCliente.setText("0");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Telefono");

        txttelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombrecliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addComponent(txtcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdiascredito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel6)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cmbmetodopago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoCliente)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtcolonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbmetodopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdiascredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(214, 214, 251));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        btnnuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnnuevoKeyPressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        btnmodificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnmodificarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnuevo)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnmodificar)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnnuevo)
                    .addComponent(btnBuscar)
                    .addComponent(btnmodificar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void ultimoRegistro()
    {
        int lasid=0;
        try
        {
             con = conexion.getConnection();
             stmt=con.createStatement();
             rs =stmt.executeQuery("select max(id_Cliente) from tblClientes ");
             if(rs.next())
            {
                lasid=rs.getInt(1)+1;
            }
            lblNoCliente.setText(lasid+"");
            con.close();
        }
        catch(SQLException ex)
        {
         JOptionPane.showMessageDialog(this,"Ocurrio el siguiente error:"+ex);
        }
    }
     
    public void limpiarcampos()
    {
        txtnombrecliente.setText("");
        txtdireccion.setText("");
        txtcolonia.setText("");
        txtdiascredito.setText("");
        cmbmetodopago.setSelectedIndex(0);
        txttelefono.setText("");
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    //Validas valores
       if ("".equals(txtnombrecliente.getText()) || "".equals(txtdireccion.getText())||"".equals(txtcolonia.getText()))
          {
              JOptionPane.showMessageDialog(null, "Favor de Rellenar los Campos necesarios");
              txtnombrecliente.requestFocus();
              return;
          }
       else
       {
           //Tomar los valor parfa guardarlos
        int numerocliente=Integer.parseInt(lblNoCliente.getText());
        String nombre =txtnombrecliente.getText();
        String direccion = txtdireccion.getText();
        String colonia = txtcolonia.getText();
        String pago= cmbmetodopago.getSelectedItem().toString();
        int tippago=0;
       String telefono = txttelefono.getText();
        
        if ("Contado".equals(pago)) 
        {
            tippago=1;
        }
        else
        {
            tippago=2;
        }
               
        String dias =txtdiascredito.getText();
        int diascredito=0;
        if ("".equals(dias)) 
        {
            diascredito=0;
        }
        else
        {
            diascredito=Integer.parseInt(txtdiascredito.getText());
        }   
        
        //Consulta para guardar datos en la base de datos
        try {           
           con = conexion.getConnection();
           stmt = con.createStatement();
           PreparedStatement psInsert= con.prepareStatement("INSERT INTO tblclientes(cliNombre,cliDireccion,cliColonia,"
                   + "cliTipoPago,cliDiasCredito,cliTelefono) VALUES (?,?,?,?,?,?)");
          psInsert.setString(1, nombre);
          psInsert.setString(2, direccion);
          psInsert.setString(3, colonia);
          psInsert.setInt(4, tippago);
          psInsert.setInt(5, diascredito);
          psInsert.setString(6, telefono);
          
          psInsert.executeUpdate();
          
          JOptionPane.showMessageDialog(null, "Se ingreso correctamente, gracias");  
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
       }
       ultimoRegistro();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbmetodopagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbmetodopagoFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_cmbmetodopagoFocusLost

    private void txtdiascreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiascreditoKeyTyped
        // TODO add your handling code here:
        
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car<=',' || car>'.')|| (car=='-'))  evt.consume();
    }//GEN-LAST:event_txtdiascreditoKeyTyped

    private void cmbmetodopagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmetodopagoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmetodopagoItemStateChanged

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        limpiarcampos();
        ultimoRegistro();
        txtnombrecliente.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
//         TODO add your handling code here:

         frmbuscaclientes buscar = new frmbuscaclientes();
         buscar.setVisible(true);
//           
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        // TODO add your handling code here:
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9') && (car<=',' || car>='.')|| (car=='-'))  evt.consume();
        
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed

    int confirmacion = JOptionPane.showConfirmDialog(null, "Los datos son los correctos?","Confirmacion", JOptionPane.YES_NO_OPTION,1);
    if(confirmacion==0)
    {
        
    
        
     if ("".equals(txtnombrecliente.getText()) || "".equals(txtdireccion.getText())||"".equals(txtcolonia.getText()))
              {
                  JOptionPane.showMessageDialog(null, "Favor de Rellenar los Campos necesarios");
                   txtnombrecliente.requestFocus();
                   return;
              }
           else
           {        // TODO add your handling code here:
            String resul[] ;
            String sql="insert ";
            int numerocliente=Integer.parseInt(lblNoCliente.getText());
            String nombre =txtnombrecliente.getText();
            String direccion = txtdireccion.getText();
            String colonia = txtcolonia.getText();
            String pago= cmbmetodopago.getSelectedItem().toString();
            int tippago=0;
           String telefono = txttelefono.getText();

            int resultado = 0;

            if ("Contado".equals(pago)) 
            {
                tippago=1;
            }
            else
            {
                tippago=2;
            }

            String dias =txtdiascredito.getText();
            int diascredito=0;
            if ("".equals(dias)) 
            {
                diascredito=0;
            }
            else
            {
                diascredito=Integer.parseInt(txtdiascredito.getText());
            }

                 con = conexion.getConnection();

            try {


               stmt = con.createStatement();
               PreparedStatement psInsert= con.prepareStatement("update tblclientes set cliNombre=?,cliDireccion=?,"
                       + "cliColonia=?,cliTipopago=?,cliDiasCredito=?,cliTelefono=? where id_Cliente=?");


              psInsert.setString(1, nombre);
              psInsert.setString(2, direccion);
              psInsert.setString(3, colonia);
              psInsert.setInt(4, tippago);
              psInsert.setInt(5, diascredito);
              psInsert.setString(6, telefono);
              psInsert.setInt(7, numerocliente);

              psInsert.executeUpdate();
              psInsert.close();

              JOptionPane.showMessageDialog(null, "Se ingreso correctamente, gracias");

            } 
            catch (SQLException e) 
            {
                JOptionPane.showMessageDialog(null, e);

            }    
           }
           limpiarcampos();
    }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void txtdiascreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiascreditoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txttelefono.requestFocus();
        }
    }//GEN-LAST:event_txtdiascreditoKeyPressed

    private void txtnombreclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreclienteKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
             txtdireccion.requestFocus();
         }
    }//GEN-LAST:event_txtnombreclienteKeyPressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        // TODO add your handling code here:
     if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
             txtcolonia.requestFocus();
         }
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtcoloniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcoloniaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
             cmbmetodopago.requestFocus();
         }
    }//GEN-LAST:event_txtcoloniaKeyPressed

    private void cmbmetodopagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbmetodopagoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
             txtdiascredito.requestFocus();
         }
    }//GEN-LAST:event_cmbmetodopagoKeyPressed

    private void txttelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
             btnAgregar.requestFocus();
         }
    }//GEN-LAST:event_txttelefonoKeyPressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            getRootPane().setDefaultButton(btnAgregar);
         }
         
        
    }//GEN-LAST:event_btnAgregarKeyPressed

    private void btnnuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnnuevoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            getRootPane().setDefaultButton(btnnuevo);
         }
    }//GEN-LAST:event_btnnuevoKeyPressed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            getRootPane().setDefaultButton(btnBuscar);
         }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void btnmodificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnmodificarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
         {
            getRootPane().setDefaultButton(btnmodificar);
         }
    }//GEN-LAST:event_btnmodificarKeyPressed

    private void txtnombreclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreclienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreclienteKeyReleased

    private void cmbmetodopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmetodopagoActionPerformed
        // TODO add your handling code here:
        String combo=cmbmetodopago.getSelectedItem().toString();
        if(combo!="Contado"){
            txtdiascredito.enable(true);
        }
        else{
            txtdiascredito.enable(false);
        }
    }//GEN-LAST:event_cmbmetodopagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmclientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> cmbmetodopago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblNoCliente;
    public static javax.swing.JTextField txtcolonia;
    public static javax.swing.JTextField txtdiascredito;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtnombrecliente;
    public static javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
