package puntoventav2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francisco Rafael
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    public frmPrincipal()
    {
        initComponents();
        this.setResizable(false);
        this.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);
    }
    
    public void deshabilitar()
    {
        mibclientes.setEnabled(false);
        mibproveedores.setEnabled(false);
        mibproductos.setEnabled(false);
        mibrealizarnotas.setEnabled(false);
        mibreeimprimirnotas.setEnabled(false);
        mibmodificarnotas.setEnabled(false);
        mibcancelarnotas.setEnabled(false);
        mibabononotas.setEnabled(false);
        mibregistrarentradas.setEnabled(false);
        mibmodificarentradas.setEnabled(false);
        mibcancelarentradas.setEnabled(false);
        mibabonoentradas.setEnabled(false);
        mibreporteventas.setEnabled(false);
        mibreporteventascliente.setEnabled(false);
        mibreportecompras.setEnabled(false);
        mibreportecomprasproveedor.setEnabled(false);
        mibreportepagonotas.setEnabled(false);
        mibreportepagoentradas.setEnabled(false);
        mibregistroinventario.setEnabled(false);
        miblistaprecios.setEnabled(false);
        mibregistrarsalidas.setEnabled(false);
        mibcancelarsalidas.setEnabled(false);
    }
    
    public static void habilitar()
    {
        mibclientes.setEnabled(true);
        mibproveedores.setEnabled(true);
        mibproductos.setEnabled(true);
        mibrealizarnotas.setEnabled(true);
        mibreeimprimirnotas.setEnabled(true);
        mibmodificarnotas.setEnabled(true);
        mibcancelarnotas.setEnabled(true);
        mibabononotas.setEnabled(true);
        mibregistrarentradas.setEnabled(true);
        mibmodificarentradas.setEnabled(true);
        mibcancelarentradas.setEnabled(true);
        mibabonoentradas.setEnabled(true);
        mibreporteventas.setEnabled(true);
        mibreporteventascliente.setEnabled(true);
        mibreportecompras.setEnabled(true);
        mibreportecomprasproveedor.setEnabled(true);
        mibreportepagonotas.setEnabled(true);
        mibreportepagoentradas.setEnabled(true);
        mibregistroinventario.setEnabled(true);
        miblistaprecios.setEnabled(true);
        mibregistrarsalidas.setEnabled(true);
        mibcancelarsalidas.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        mnbprincipal = new javax.swing.JMenuBar();
        mniclientes = new javax.swing.JMenu();
        mibclientes = new javax.swing.JMenuItem();
        mibproveedores = new javax.swing.JMenuItem();
        mibproductos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mibrealizarnotas = new javax.swing.JMenuItem();
        mibreeimprimirnotas = new javax.swing.JMenuItem();
        mibmodificarnotas = new javax.swing.JMenuItem();
        mibcancelarnotas = new javax.swing.JMenuItem();
        mibabononotas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mibregistrarentradas = new javax.swing.JMenuItem();
        mibmodificarentradas = new javax.swing.JMenuItem();
        mibcancelarentradas = new javax.swing.JMenuItem();
        mibabonoentradas = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mibreporteventas = new javax.swing.JMenuItem();
        mibreporteventascliente = new javax.swing.JMenuItem();
        mibreportecompras = new javax.swing.JMenuItem();
        mibreportecomprasproveedor = new javax.swing.JMenuItem();
        mibreportepagonotas = new javax.swing.JMenuItem();
        mibreportepagoentradas = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        mibregistroinventario = new javax.swing.JMenuItem();
        miblistaprecios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mibregistrarsalidas = new javax.swing.JMenuItem();
        mibcancelarsalidas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        mniclientes.setText("Registros");
        mniclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniclientesMouseClicked(evt);
            }
        });

        mibclientes.setText("Clientes");
        mibclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibclientesActionPerformed(evt);
            }
        });
        mniclientes.add(mibclientes);

        mibproveedores.setText("Proveedores");
        mibproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibproveedoresActionPerformed(evt);
            }
        });
        mniclientes.add(mibproveedores);

        mibproductos.setText("Productos");
        mibproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibproductosActionPerformed(evt);
            }
        });
        mniclientes.add(mibproductos);

        mnbprincipal.add(mniclientes);

        jMenu5.setText("Notas");

        mibrealizarnotas.setText("Realizar");
        mibrealizarnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibrealizarnotasActionPerformed(evt);
            }
        });
        jMenu5.add(mibrealizarnotas);

        mibreeimprimirnotas.setText("Reimprimir");
        mibreeimprimirnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreeimprimirnotasActionPerformed(evt);
            }
        });
        jMenu5.add(mibreeimprimirnotas);

        mibmodificarnotas.setText("Modificar");
        mibmodificarnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibmodificarnotasActionPerformed(evt);
            }
        });
        jMenu5.add(mibmodificarnotas);

        mibcancelarnotas.setText("Cancelar");
        mibcancelarnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibcancelarnotasActionPerformed(evt);
            }
        });
        jMenu5.add(mibcancelarnotas);

        mibabononotas.setText("Abono");
        mibabononotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibabononotasActionPerformed(evt);
            }
        });
        jMenu5.add(mibabononotas);

        mnbprincipal.add(jMenu5);

        jMenu7.setText("Entradas");

        mibregistrarentradas.setText("Registrar");
        mibregistrarentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibregistrarentradasActionPerformed(evt);
            }
        });
        jMenu7.add(mibregistrarentradas);

        mibmodificarentradas.setText("Modificar");
        mibmodificarentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibmodificarentradasActionPerformed(evt);
            }
        });
        jMenu7.add(mibmodificarentradas);

        mibcancelarentradas.setText("Cancelar");
        mibcancelarentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibcancelarentradasActionPerformed(evt);
            }
        });
        jMenu7.add(mibcancelarentradas);

        mibabonoentradas.setText("Abono Entradas");
        mibabonoentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibabonoentradasActionPerformed(evt);
            }
        });
        jMenu7.add(mibabonoentradas);

        mnbprincipal.add(jMenu7);

        jMenu8.setText("Reportes ");

        mibreporteventas.setText("Reporte de Ventas General");
        mibreporteventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreporteventasActionPerformed(evt);
            }
        });
        jMenu8.add(mibreporteventas);

        mibreporteventascliente.setText("Reporte de Ventas Por Cliente");
        mibreporteventascliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreporteventasclienteActionPerformed(evt);
            }
        });
        jMenu8.add(mibreporteventascliente);

        mibreportecompras.setText("Reporte de Compras General");
        mibreportecompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreportecomprasActionPerformed(evt);
            }
        });
        jMenu8.add(mibreportecompras);

        mibreportecomprasproveedor.setText("Reporte de Compras Por Proveedor");
        mibreportecomprasproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreportecomprasproveedorActionPerformed(evt);
            }
        });
        jMenu8.add(mibreportecomprasproveedor);

        mibreportepagonotas.setText("Reporte de Pagos de Notas");
        mibreportepagonotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreportepagonotasActionPerformed(evt);
            }
        });
        jMenu8.add(mibreportepagonotas);

        mibreportepagoentradas.setText("Reporte de Pagos de  Entradas");
        mibreportepagoentradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibreportepagoentradasActionPerformed(evt);
            }
        });
        jMenu8.add(mibreportepagoentradas);

        mnbprincipal.add(jMenu8);

        jMenu9.setText("Inventario");

        mibregistroinventario.setText("Registro");
        mibregistroinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibregistroinventarioActionPerformed(evt);
            }
        });
        jMenu9.add(mibregistroinventario);

        miblistaprecios.setText("Lista de Precios");
        miblistaprecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miblistapreciosActionPerformed(evt);
            }
        });
        jMenu9.add(miblistaprecios);

        mnbprincipal.add(jMenu9);

        jMenu3.setText("Salidas");

        mibregistrarsalidas.setText("Registrar");
        mibregistrarsalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibregistrarsalidasActionPerformed(evt);
            }
        });
        jMenu3.add(mibregistrarsalidas);

        mibcancelarsalidas.setText("Cancelar");
        mibcancelarsalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mibcancelarsalidasActionPerformed(evt);
            }
        });
        jMenu3.add(mibcancelarsalidas);

        mnbprincipal.add(jMenu3);

        setJMenuBar(mnbprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mibrealizarnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibrealizarnotasActionPerformed
        // TODO add your handling code here:
       deshabilitar();
       frmnotas notas = new frmnotas();
       notas.setVisible(true);
    }//GEN-LAST:event_mibrealizarnotasActionPerformed

    private void mniclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniclientesMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_mniclientesMouseClicked

    private void mibreeimprimirnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreeimprimirnotasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmreimprimirnotas reeimprimir = new frmreimprimirnotas();
        reeimprimir.setVisible(true);
       
    }//GEN-LAST:event_mibreeimprimirnotasActionPerformed

    private void mibmodificarnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibmodificarnotasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscarmodificarnotas modificar= new frmbuscarmodificarnotas();
        modificar.setVisible(true);
    }//GEN-LAST:event_mibmodificarnotasActionPerformed

    private void mibcancelarnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibcancelarnotasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscacancelarnotas cancelar = new frmbuscacancelarnotas();
        cancelar.setVisible(true);
    }//GEN-LAST:event_mibcancelarnotasActionPerformed

    private void mibreporteventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreporteventasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmreporteventasgeneral reporte = new frmreporteventasgeneral();
        reporte.setVisible(true);
    }//GEN-LAST:event_mibreporteventasActionPerformed

    private void mibabononotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibabononotasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscapagonotas pg= new frmbuscapagonotas();
        pg.setVisible(true);
    }//GEN-LAST:event_mibabononotasActionPerformed

    private void mibregistrarentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibregistrarentradasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmentradas en = new frmentradas();
        en.setVisible(true);
    }//GEN-LAST:event_mibregistrarentradasActionPerformed

    private void mibreporteventasclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreporteventasclienteActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmreporteventascliente repor = new frmreporteventascliente();
        repor.setVisible(true);
        
    }//GEN-LAST:event_mibreporteventasclienteActionPerformed

    private void mibregistroinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibregistroinventarioActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frminventario inventario = new frminventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_mibregistroinventarioActionPerformed

    private void miblistapreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miblistapreciosActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmlistaarticulos lista = new frmlistaarticulos();
        lista.setVisible(true);
    }//GEN-LAST:event_miblistapreciosActionPerformed

    private void mibreportecomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreportecomprasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmReporteCompras compras= new frmReporteCompras();
        compras.setVisible(true);
    }//GEN-LAST:event_mibreportecomprasActionPerformed

    private void mibmodificarentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibmodificarentradasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscaentradasmodificar modificar = new frmbuscaentradasmodificar();
        modificar.setVisible(true);
        
    }//GEN-LAST:event_mibmodificarentradasActionPerformed

    private void mibcancelarentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibcancelarentradasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscaentradascancelar cancelar = new frmbuscaentradascancelar();
        cancelar.setVisible(true);
    }//GEN-LAST:event_mibcancelarentradasActionPerformed

    private void mibreportepagonotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreportepagonotasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmReportepagosnotas pago = new frmReportepagosnotas();
        pago.setVisible(true);
    }//GEN-LAST:event_mibreportepagonotasActionPerformed

    private void mibreportepagoentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreportepagoentradasActionPerformed
        // TODO add your handling code here:|
        deshabilitar();
        frmReportepagosentradas pago = new frmReportepagosentradas();
        pago.setVisible(true);
        deshabilitar();
    }//GEN-LAST:event_mibreportepagoentradasActionPerformed

    private void mibabonoentradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibabonoentradasActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmbuscapagoentradas abono = new frmbuscapagoentradas();
        abono.setVisible(true);
    }//GEN-LAST:event_mibabonoentradasActionPerformed

    private void mibreportecomprasproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibreportecomprasproveedorActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmReporteComprasProveedor reporte = new frmReporteComprasProveedor();
        reporte.setVisible(true);
    }//GEN-LAST:event_mibreportecomprasproveedorActionPerformed

    private void mibclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibclientesActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmclientes clientes = new frmclientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_mibclientesActionPerformed

    private void mibproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibproveedoresActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmproveedores provedor = new frmproveedores();
        provedor.setVisible(true);
    }//GEN-LAST:event_mibproveedoresActionPerformed

    private void mibproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibproductosActionPerformed
        // TODO add your handling code here:
        deshabilitar();
        frmarticulos articulos = new frmarticulos();
        articulos.setVisible(true);
    }//GEN-LAST:event_mibproductosActionPerformed

    private void mibcancelarsalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibcancelarsalidasActionPerformed
        // TODO add your handling code here:
        frmbuscasalidascancelar cancelar = new frmbuscasalidascancelar();
        cancelar.setVisible(true);
        deshabilitar();
    }//GEN-LAST:event_mibcancelarsalidasActionPerformed

    private void mibregistrarsalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mibregistrarsalidasActionPerformed
        // TODO add your handling code here:
        frmrsalidas salida = new frmrsalidas();
        salida.setVisible(true);
        deshabilitar();
    }//GEN-LAST:event_mibregistrarsalidasActionPerformed

    /**
 * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JMenuItem mibabonoentradas;
    public static javax.swing.JMenuItem mibabononotas;
    public static javax.swing.JMenuItem mibcancelarentradas;
    public static javax.swing.JMenuItem mibcancelarnotas;
    public static javax.swing.JMenuItem mibcancelarsalidas;
    public static javax.swing.JMenuItem mibclientes;
    public static javax.swing.JMenuItem miblistaprecios;
    public static javax.swing.JMenuItem mibmodificarentradas;
    public static javax.swing.JMenuItem mibmodificarnotas;
    public static javax.swing.JMenuItem mibproductos;
    public static javax.swing.JMenuItem mibproveedores;
    public static javax.swing.JMenuItem mibrealizarnotas;
    public static javax.swing.JMenuItem mibreeimprimirnotas;
    public static javax.swing.JMenuItem mibregistrarentradas;
    public static javax.swing.JMenuItem mibregistrarsalidas;
    public static javax.swing.JMenuItem mibregistroinventario;
    public static javax.swing.JMenuItem mibreportecompras;
    public static javax.swing.JMenuItem mibreportecomprasproveedor;
    public static javax.swing.JMenuItem mibreportepagoentradas;
    public static javax.swing.JMenuItem mibreportepagonotas;
    public static javax.swing.JMenuItem mibreporteventas;
    public static javax.swing.JMenuItem mibreporteventascliente;
    public static javax.swing.JMenuBar mnbprincipal;
    private javax.swing.JMenu mniclientes;
    // End of variables declaration//GEN-END:variables
}
